### ISSUE TITLE
ガイドの組み込みテーマmiyadaiku.themes.ipynbのload_cssについて

### ISSUE THREAD

**Issue by ghost** [miyadaiku/miyadaiku-docs#1]
組み込みテーマのmiyadaiku.themes.ipynb(https://miyadaiku.github.io/ja/guide/builtin-themes.html#ipynb) についての確認です.

> テンプレートの head 要素で、ipynb モジュールの load_css(page) を呼び出し、CSSファイルを指定する link 要素を出力します。

とあり, 記載されているサンプルコードは

```
{{ ipynb.load_css(page) }}
```

となっていますが, 正しくは, 

```
{{ ipynb.set_header() }}
```

ではないでしょうか.

前者ではエラー(UndefinedError: 'jinja2.environment.TemplateModule object' has no attribute 'load_css') となりました.

サンプル (https://github.com/miyadaiku/miyadaiku-docs/blob/master/samples/ipynb/templates/page_article.html) を確認したところ, 後者のようになっており, こちらではうまく動作しました.

**Comment by ghost** [comment]
申し訳ありません, post先を間違えました.  改めて, https://github.com/miyadaiku/miyadaiku.github.io こちらに投稿させていただきます.

**Comment by atsuoishimoto** [comment]
ありがとうございます。チケットはこちらでも大丈夫です。

ご指摘のとおり、{{ ipynb.set_header() }} が正解で、現在は修正済みとなっています。

ご連絡ありがとうございました
